ingester:
  exporters:
    enabled: false
    export-datas: [cbpf-net-span]
    export-data-types: [service_info]
    export-custom-k8s-labels-regexp:
    prometheus-exporter:
      - namespace: test
        endpoint: 127.0.0.1:4317
        protocol-filter: [http, https, http2, https2, mysql, redis, kafka, mqtt, grpc, protobuf_rpc]
        queue-count: 4
        queue-size: 100000
        export-datas: [ebpf-sys-span]
        export-data-types: [ tracing_info,network_layer,flow_info,transport_layer,application_layer,metrics ]
        export-custom-k8s-labels-regexp:
        export-only-with-traceid: true
